### ISSUE TITLE
unknown error

### ISSUE THREAD

**Issue by ChinmayNayak007** [emreozdil/GEM#3]
hi,
after taking photo in registration process i am receiving following error
**unknow error: please check response** 

i have changed the client to
let client = MPOFaceServiceClient(endpointAndSubscriptionKey: "https://westcentralus.api.cognitive.microsoft.com/face/v1.0", key: "b08335bea42540398151c9a9f5b8c661")!

i am using trial face api key.

please reply to mail id
sachin.baburao@3i-infotech.com

**Comment by emreozdil** [comment]
Your issue is about the Microsoft Face API. Look at this [repository](https://github.com/Microsoft/Cognitive-Face-iOS).
I suppose your endpointAndSubscriptionKey is wrong when I review the source code of Microsoft Face API.
```
- (id)initWithEndpointAndSubscriptionKey:(NSString *)endpoint key:(NSString *)key {

    self = [super init];
    if (self) {
        if(![endpoint hasSuffix:@"/"]){
            endpoint = [endpoint stringByAppendingString:@"/"];
        }
        self.endpoint = endpoint;
        self.subscriptionKey = key;
    }

    return self;
}
```

**Comment by ChinmayNayak007** [comment]
following are my microsoft  face api credentials.

**Endpoint: https://westcentralus.api.cognitive.microsoft.com/face/v1.0

Key 1: b08335bea42540398151c9a9f5b8c661

Key 2: 9c1460599ecb49829f9f7d7fc879017e ** 

** i am facing unknown response error **

**Comment by emreozdil** [comment]
My advice use default endpoint service and ```- (id)initWithSubscriptionKey:(NSString *)key;``` this function. Because I can try Europe server them I faced same error too.

Note: ```static NSString *const DefaultEndpoint = @"https://westus.api.cognitive.microsoft.com/face/v1.0/";```
