### ISSUE TITLE
unknown response error.

### ISSUE THREAD

**Issue by ChinmayNayak007** [emreozdil/GEM#4]
when i click take picture button i am facing following error:

[Snapshotting] Snapshotting a view (0x10a015400, UIKeyboardImpl) that is not in a visible window requires afterScreenUpdates:YES.

unknown response error.

**Comment by ChinmayNayak007** [comment]
i think this error is related to uploading image Data to firebase
so what changes should i make with firebase to make this work.
i am using  my own firebase project for this.  

let uploadTask = imageRef.putData(dataImage, metadata: nil, completion: { (metadata, error) in
                        if error != nil {
                            let user = Auth.auth().currentUser
                            user?.delete { error in
                                if let error = error {
                                    print(error)
                                } else {
                                    print("User successfully deleted")
                                }
                            }
                            let alert = UIAlertController(title: "Error", message: error?.localizedDescription ?? "error", preferredStyle: .alert)
                            let action = UIAlertAction(title: "OK", style: .default, handler: { (action) in
                                self.dismiss(animated: true, completion: nil)
                            })
                            alert.addAction(action)
                            self.present(alert, animated: true, completion: nil)
                            return
                        }

**Comment by emreozdil** [comment]
In this project, we use Firebase Auth, Database, and Storage system. 
Important:
    Authentication -> Sign In Methods
    Database -> Rules
    Storage -> Rules

Each user information saved in the database and user photos saved in storage with a user id.

**Comment by ChinmayNayak007** [comment]
thanks for your help, 
i have to change the storage rules. 
please post your storage rules so i can follow the same.

**Comment by ChinmayNayak007** [comment]
thanks a lot,
i fixed the issue.
